name:                stopping-time-server
version:             0.1.0.0
github:              "zelinf/stopping-time"
license:             BSD3
author:              "Zelin Feng"
maintainer:          "fengzlin@mail2.sysu.edu.cn"
copyright:           "Copyright Zelin Feng 2018"

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Web

description:         Please see the README on GitHub at <https://github.com/zelinf/markov-demo#readme>

flags:
  production:
    description: Whether to build for production environment
    manual: true
    default: False

dependencies:
- base >= 4.7 && < 5
- matrix
- text
- vector
- mtl
- transformers
- servant
- servant-server
- servant-docs
- warp
- wai-cors
- bytestring
- aeson
- file-embed
- MonadRandom
- random

library:
  source-dirs: src
  when:
    - condition: flag(production)
      cpp-options: -DPRODUCTION


executables:
  server:
    main:                Server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stopping-time-server
  js-gen:
    main: JSGen.hs
    source-dirs: app
    ghc-options:
    - -threaded
    dependencies:
    - stopping-time-server
    - servant-js
    - optparse-applicative
    when:
      - condition: flag(production)
        cpp-options: -DPRODUCTION
  doc-gen:
    main: DocGen.hs
    source-dirs: app
    ghc-options:
    - -threaded
    dependencies:
    - stopping-time-server
    - servant-pandoc
    - pandoc

tests:
  server-unit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stopping-time-server
    - hspec
    - QuickCheck
