name:                stopping-time-server
version:             0.1.0.0
github:              "zelinf/markov-demo"
license:             BSD3
author:              "Zelin Feng"
maintainer:          "fengzlin@mail2.sysu.edu.cn"
copyright:           "Copyright Zelin Feng 2018"

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Web

description:         Please see the README on GitHub at <https://github.com/zelinf/markov-demo#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- text
- vector
- transformers
- monads-tf
- servant
- servant-server
- bytestring
- aeson

library:
  source-dirs: src

executables:
  stopping-time-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stopping-time-server

tests:
  server-unit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stopping-time-server
    - hspec
    - QuickCheck
